Issue 95: wait4all fixes
vecma-project/QCG-PilotJob pull request #152
Opened 2022-03-04 14:39 UTC by LourensVeen

This fixes the two issues with `wait4all` mentioned in #95.

I have no experience with asyncio, so I may be wrong, but I think the potential case in where a job finishes just before the call to `self._publish_no_jobs_event` on line 654 of `manager.py` and sends a NO_JOBS event so that we get two stacked on top of each other cannot happen, because there is no `await` and so asyncio cannot context switch to handling the completion of the process in the `Executor`. But please check that that's the case.

For the new `wait4all` algorithm in `api/manager.py`, when the function is called there are three possible states the system can be in: 1) there's at least one job still running, 2) all jobs have finished and all notifications have been received, and 3) all jobs have finished but there are still pending notifications. On the client side, we can either have a status poller or not.

We first do a synchronous check to see if no jobs are running. If this returns `False`, then we must be in case 1), if it's `True` then we have case 2) or 3). If we don't have a poller, then we sleep-loop until the synchronous check returns `True`. If we do have a poller, then we check if there are pending events. At this point, we have the following possibilities:

A) `not all_finished and not events`: we're in case 1)
B) `not all_finished and events`: we're in case 1) and the last job just finished
C) `all_finished and not events`: we're in case 2)
D) `all_finished and events`: we're in case 3)

For A), we process the zero events we have, and start polling until we get events and find a NO_JOB, and return
For B), we process the events we have up to and including the NO_JOBS, and return
For C), we return immediately
For D), we process the events we have up to and including the NO_JOBS, and return

I replaced `not_finished` with `all_finished` because the double negation was giving me a headache :-).

I think this is correct, and I could reproduce the problem with the original code but not with this one.

2022-03-28 14:48 UTC, pkopta requested changes
I wonder if a better solution would not be to move the `_publish_no_jobs_event()` function to the end of `change_job_state` function, in an example form:
```
        if state.is_finished() and self.is_all_jobs_finished():
            self._publish_no_jobs_event()
```
I think that putting this code in the `_schedule_loop` function may generate many `NO_JOBS` notifications

2022-03-28 14:52 UTC, pkopta reviewed
I think this change should work ok, but I wonder if the bullet-proof solution would not be to ignore any of waiting events and status notifications before the first `allJobsFinished` request ? What do you think ?

2022-03-28 16:17 UTC, LourensVeen commented
I don't think it will generate many `NO_JOBS` notifications, one is only generated if the scheduling queue had something in it before this iteration of the scheduling loop and is now empty, and also nothing is running. So that only happens if the last remaining jobs in the queue weren't feasible. (If they have started then they're either still running, or their finishing hasn't been processed yet so they're still running for administrative purposes at least, and then the callback of the last one will send the NO_JOBS when it gets processed on the next await.)

I think I agree that it would be nicer to add the call to `_publish_no_jobs_event()` to `change_job_state()`, since it already fires the other notifications. Actually, maybe it should be in `_publish_status_events()`? Could `_publish_no_jobs_event` simply be merged into that?

If we drain the event queue and then call `allJobsFinished`, can we get into a situation where some new events are added by finishing jobs after we've finished draining, but before we call `allJobsFinished`? Then `allJobsFinished` would return `True` and we return, but there would still be events stuck in the queue. I guess they'll get eaten by the next call though.

I have to say, all this sending of events which are then sometimes ignored and sometimes not is pretty tricky to keep track of. I'm looking at it again a few weeks after having written it and I'm glad I added the explanation above!

A simpler option could be to keep a local mirror of the job states in the client, then make sure we always read all events and update the local state accordingly each time we process one (essentially log-shipping based database replication). Then to `wait4all()`, we could check locally if there's anything running, and if so block on the message socket until a message arrives, update the state, then check again locally and repeat. Then all you need is JOB_STATUS, with JOB_FINISHED and NO_JOBS disappearing entirely because all the logic is now client-side. You'll still receive 1k messages for 1k jobs, but only once per job, not on every sleep-loop iteration of `wait4all()`.

2022-03-29 07:25 UTC, LourensVeen commented
Actually, are we assuming that there's a single single-threaded client, and so that no new jobs can be posted while we're in `wait4all()`?

2022-03-29 08:43 UTC, pkopta commented
To be honest, I did not take multithreading into account when implementing the notification mechanism. According to my knowledge, so far in all scenarios QCG-PilotJob has been used in single-threaded clients. Do you think that multithreading is a real use-case or we just should clearly specify in documentation as single-thread safe library ?

2022-03-29 09:47 UTC, LourensVeen commented
I would think that at least the vast majority of users is just going to write a Python script to submit jobs, and that it will all be singlethreaded. There might be a case where someone starts up a QCG-PJ manager and connects to it from different Python scripts running simultaneously, but I can't really think of a concrete use case. I would say it's fine to just declare the whole thing single-client single-thread. Clearly documenting it is a good idea, because if someone tries anyway they may end up with difficult-to-debug hangs.

We'll have to see what to do here, I'm getting to the end of my hours on this project, and I need to get the next version of MUSCLE3 out the door (and I'm not using this there). I could merge `_publish_no_jobs_event` into `_publish_status_events` quickly, but bigger changes would require getting the code back into my brain and it may take a bit more time to find the time for that. I think drain-and-check will work, and not be very hard to implement. I still like having `allJobsFinished` post a `NO_JOBS`, but it's probably not worth the time.

2022-03-31 14:22 UTC, merged